### ISSUE TITLE
Website SSL is using OLD/Expired 

### ISSUE THREAD

**Issue by srbala** [poeml/mirrorbrain#184]
The link to https://mirrorbrain.org/ is using OLD/Expired certificate. Please update the site SSL. Please make use free Let's encrypt certs

**Comment by alicaccs** [comment]
And the https config is bad by 2021 standards, still supporting SSLv2/3 and not supporting TLSv1.2+. Latest Firefox will refuse to connect the site by default.

Please update the https config, or at least enable the insecure http version as last resort...

**Comment by srbala** [comment]
@poeml Looks like you have moved on to other assignments. Any plans to assign external collaborators to manage the site/repo

**Comment by poeml** [comment]
Happy to report that with the server update, the site now runs on a contemporary platform and uses TLS with valid certificates.

**Comment by poeml** [comment]
> @poeml Looks like you have moved on to other assignments. Any plans to assign external collaborators to manage the site/repo

I'll be happy about any help, indeed!
